swagger: "2.0"
info:
    title: Sailpoint integration
    description: Implements the integration API for sailpoint
    version: ""
host: localhost:8088
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /account:
        post:
            tags:
                - account
            summary: create account
            description: Create an account
            operationId: account#create
            parameters:
                - name: Authorization
                  in: header
                  description: Basic Auth security using Basic scheme (https://tools.ietf.org/html/rfc7617)
                  required: true
                  type: string
                - name: CreateRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/AccountCreateRequestBody'
            responses:
                "201":
                    description: Created response.
            schemes:
                - http
            security:
                - BasicAuth_header_Authorization: []
    /account/{accountId}:
        delete:
            tags:
                - account
            summary: delete account
            description: Delete an account
            operationId: account#delete
            parameters:
                - name: accountId
                  in: path
                  description: Account ID
                  required: true
                  type: string
                - name: Authorization
                  in: header
                  description: Basic Auth security using Basic scheme (https://tools.ietf.org/html/rfc7617)
                  required: true
                  type: string
            responses:
                "204":
                    description: No Content response.
            schemes:
                - http
            security:
                - BasicAuth_header_Authorization: []
    /aggregate/accounts:
        get:
            tags:
                - aggregate
            summary: accounts aggregate
            description: Account aggregation. Returns all known accounts
            operationId: aggregate#accounts
            parameters:
                - name: Authorization
                  in: header
                  description: Basic Auth security using Basic scheme (https://tools.ietf.org/html/rfc7617)
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/AccountResponse'
                "403":
                    description: Forbidden response.
                    schema:
                        $ref: '#/definitions/AggregateAccountsPermissionDeniedResponseBody'
            schemes:
                - http
            security:
                - BasicAuth_header_Authorization: []
    /aggregate/groups:
        get:
            tags:
                - aggregate
            summary: groups aggregate
            description: Group aggregation. Returns list of all known groups
            operationId: aggregate#groups
            parameters:
                - name: Authorization
                  in: header
                  description: Basic Auth security using Basic scheme (https://tools.ietf.org/html/rfc7617)
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/groupResponse'
                "403":
                    description: Forbidden response.
                    schema:
                        $ref: '#/definitions/AggregateGroupsPermissionDeniedResponseBody'
            schemes:
                - http
            security:
                - BasicAuth_header_Authorization: []
    /test:
        get:
            tags:
                - test
            summary: test test
            operationId: test#test
            responses:
                "200":
                    description: OK response.
            schemes:
                - http
definitions:
    AccountCreateRequestBody:
        title: AccountCreateRequestBody
        type: object
        properties:
            email:
                type: string
                description: Email of user
                example: amos@hostedzonehere.com
            login:
                type: string
                description: Login of user
                example: amos
            name:
                type: string
                description: Name of user
                example: Amos Burton
        example:
            email: amos@hostedzonehere.com
            login: amos
            name: Amos Burton
    AccountResponse:
        title: AccountResponse
        type: object
        properties:
            email:
                type: string
                description: Email of user
                example: amos@hostedzonehere.com
            login:
                type: string
                description: Login of user
                example: amos
            name:
                type: string
                description: Name of user
                example: Amos Burton
        example:
            email: amos@hostedzonehere.com
            login: amos
            name: Amos Burton
    AggregateAccountsPermissionDeniedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: accounts_PermissionDenied_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    AggregateGroupsPermissionDeniedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: groups_PermissionDenied_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    groupResponse:
        title: groupResponse
        type: object
        properties:
            guid:
                type: string
                description: GUID of group
                example: ac32dcb3-3a58-4bfc-b801-6609681ec712
            name:
                type: string
                description: Name of group
                example: GROUPNAME
        example:
            guid: ac32dcb3-3a58-4bfc-b801-6609681ec712
            name: GROUPNAME
securityDefinitions:
    BasicAuth_header_Authorization:
        type: basic
        description: Use client ID and client secret to authenticate
